import { Product } from "@/types/bestsellers/bestsellers";

// Default product data with 8 items
export const defaultProducts: Product[] = [
  {
    id: 1,
    name: "Matte Foundation Dry Skin",
    price: 40,
    originalPrice: 50,
    rating: 4.8,
    reviewCount: 102,
    image: "/assets/images/best1.jpg",
    discount: 10,
    backgroundColor: "bg-orange-100",
    isNew: false,
    isFavorite: false,
  },
  {
    id: 2,
    name: "Primer Moisturizing Cream",
    price: 84,
    originalPrice: 120,
    rating: 4.6,
    reviewCount: 500,
    image: "/assets/images/best2.jpg",
    discount: 10,
    backgroundColor: "bg-pink-100",
    isNew: false,
    isFavorite: false,
  },
  {
    id: 3,
    name: "BB Cream SPF 30",
    price: 35,
    originalPrice: 50,
    rating: 4.3,
    reviewCount: 250,
    image: "/assets/images/hemp.jpg",
    discount: 10,
    backgroundColor: "bg-blue-100",
    isNew: false,
    isFavorite: false,
  },
  {
    id: 4,
    name: "CC Cream Multi-Tone",
    price: 52,
    originalPrice: 68,
    rating: 4.5,
    reviewCount: 189,
    image: "/assets/images/silajit.jpg",
    discount: 15,
    backgroundColor: "bg-purple-100",
    isNew: true,
    isFavorite: false,
  },
  {
    id: 5,
    name: "Concealer Long-Lasting",
    price: 28,
    originalPrice: 35,
    rating: 4.7,
    reviewCount: 324,
    image: "/assets/images/jit.jpg",
    discount: 20,
    backgroundColor: "bg-green-100",
    isNew: false,
    isFavorite: false,
  },
];
