import { Product } from "@/types/bestsellers/bestseller-nav";

export const products: Product[] = [
  {
    id: 1,
    name: "Hemp Bag",
    price: 29.99,
    originalPrice: null,
    rating: 4.2,
    reviews: 578,
    image: "/assets/images/bag.jpg",
    category: "Hemp Item",
    tags: ["Eco-Friendly"],
    description:
      "Premium organic cotton t-shirt made from 100% sustainable materials. Soft, breathable, and perfect for everyday wear. This eco-friendly option combines comfort with environmental consciousness.",
    features: [
      "100% Organic Cotton",
      "Machine Washable",
      "Sustainable Production",
      "Comfortable Fit",
      "Hypoallergenic",
    ],
    stock: 45,
    shipping: "Free shipping on orders over $50",
    warranty: "1 year",
  },
  {
    id: 2,
    name: "Everest Silajit",
    price: 39.99,
    originalPrice: 59.99,
    rating: 4.0,
    reviews: 324,
    image: "/assets/images/best2.jpg",
    category: "Shilajit",
    tags: [],
    description:
      "Fast wireless charging pad compatible with all Qi-enabled devices. Sleek design with LED indicator and overheating protection. Perfect for home and office use.",
    features: [
      "Qi Wireless Charging",
      "LED Status Indicator",
      "Overheating Protection",
      "Non-slip Base",
      "Fast Charging Support",
    ],
    stock: 23,
    shipping: "Free shipping",
    expiry: "Best within 2 years of roast date",
  },
  {
    id: 3,
    name: "Minimalist Desk Lamp",
    price: 89.99,
    originalPrice: null,
    rating: 4.5,
    reviews: 156,
    image: "/assets/images/feltitem2.jpg",
    category: "Felt Item",
    tags: [],
    description:
      "Modern minimalist desk lamp with adjustable brightness and color temperature. Perfect for work and study environments. Energy-efficient LED technology with long lifespan.",
    features: [
      "Adjustable Brightness",
      "Color Temperature Control",
      "Touch Controls",
      "Energy Efficient LED",
      "Flexible Arm",
    ],
    stock: 12,
    shipping: "Free shipping",
    warranty: "6 months",
  },
  {
    id: 4,
    name: "Gourmet Coffee Beans",
    price: 24.99,
    originalPrice: 34.99,
    rating: 4.3,
    reviews: 1891,
    image: "/assets/images/silajit.jpg",
    category: "Shilajit",
    tags: ["Best Seller"],
    description:
      "Premium single-origin coffee beans sourced from high-altitude farms. Rich, complex flavor with notes of chocolate and caramel. Ethically sourced and fair trade certified.",
    features: [
      "Single Origin",
      "Fair Trade Certified",
      "Freshly Roasted",
      "Whole Bean",
      "Ethical Sourcing",
    ],
    stock: 23,
    shipping: "Free shipping",
    expiry: "Best within 2 years of roast date",
  },
  {
    id: 5,
    name: "Honey",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.4,
    reviews: 892,
    image: "/assets/images/honey.jpg",
    category: "Wildhoney",
    tags: ["Trending"],
    description:
      "Premium wireless headphones with active noise cancellation and long battery life. Crystal clear sound quality with deep bass response.",
    features: [
      "Active Noise Cancellation",
      "30-hour Battery Life",
      "Quick Charge",
      "Bluetooth 5.0",
      "Foldable Design",
    ],
    stock: 34,
    shipping: "Free shipping",
    expiry: "1 year",
  },

  {
    id: 6,
    name: "Felt Sitting",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.4,
    reviews: 892,
    image: "/assets/images/feltitem1.jpg",
    category: "Felt Item",
    tags: ["Trending"],
    description:
      "Premium wireless headphones with active noise cancellation and long battery life. Crystal clear sound quality with deep bass response.",
    features: [
      "Active Noise Cancellation",
      "30-hour Battery Life",
      "Quick Charge",
      "Bluetooth 5.0",
      "Foldable Design",
    ],
    stock: 34,
    shipping: "Free shipping",
    warranty: "1 year",
  },
  {
    id: 7,
    name: "Felt Bags",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.4,
    reviews: 892,
    image: "/assets/images/bags.jpg",
    category: "Hemp Item",
    tags: ["Trending"],
    description:
      "Premium wireless headphones with active noise cancellation and long battery life. Crystal clear sound quality with deep bass response.",
    features: [
      "Active Noise Cancellation",
      "30-hour Battery Life",
      "Quick Charge",
      "Bluetooth 5.0",
      "Foldable Design",
    ],
    stock: 34,
    shipping: "Free shipping",
    warranty: "1 year",
  },
  {
    id: 8,
    name: "Wild Honey",
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.4,
    reviews: 892,
    image: "/assets/images/wildhoney.jpg",
    category: "Wildhoney",
    tags: ["Trending"],
    description:
      "Premium wireless headphones with active noise cancellation and long battery life. Crystal clear sound quality with deep bass response.",
    features: [
      "Active Noise Cancellation",
      "30-hour Battery Life",
      "Quick Charge",
      "Bluetooth 5.0",
      "Foldable Design",
    ],
    stock: 34,
    shipping: "Free shipping",
    expiry: "1 year",
  },
];
